name: 'Custom Deploy In Kubernates'
description: 'Deploy to Dev Cluster'
inputs:
  repo:
    description: 'Repository name'
    required: true
  branch:
    description: 'Branch name'
    required: true
  commit-hash:
    description: 'Commit hash'
    required: true
  github-token:
    description: 'GitHub PAT to commit fleet-repo'
    required: true
  git-username:
    description: 'Git username'
    required: true
  git-email:
    description: 'Git e-mail'
    required: true
  fleet-repo:
    description: 'Fleet repo'
    required: true
  fleet-values-path:
    description: 'Fleet values.yaml path'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clone Repository And Update
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.fleet-repo }}
        ref: ${{ inputs.branch }}
        token: ${{ inputs.github-token }}

    - name: Configure Git
      shell: bash
      env:
        GITHUB_USERNAME: ${{ inputs.git-username }}
        GITHUB_EMAIL: ${{ inputs.git-email }}
      run: curl -o- https://raw.githubusercontent.com/alvelive/deploy/d92d8e84b5cc1035e5e0cfaf3bfbc1e879dd3711/configure_git.sh | bash

    - name: Replace content
      shell: bash
      run: |
        sed -i '/^${{ inputs.repo }}:/ { n; s/.*/  imageTag: "${{ inputs.commit-hash }}"/; }' '${{ inputs.fleet-values-path }}'

    - name: Update Fleet
      shell: bash
      env:
        GITHUB_REPO: ${{ inputs.fleet-repo }}
        GITHUB_BRANCH: ${{ inputs.branch }}
        GITHUB_SHA: ${{ inputs.commit-hash }}
      run: curl -o- https://raw.githubusercontent.com/alvelive/deploy/d92d8e84b5cc1035e5e0cfaf3bfbc1e879dd3711/commit_changes.sh | bash
