name: 'Custom Deploy In Kubernates'
description: 'Deploy to Dev Cluster'
inputs:
  repo:
    description: 'Repository name'
    required: true
  branch:
    description: 'Branch name'
    required: true
  commit-hash:
    description: 'Commit hash'
    required: true
  github-token:
    description: 'GitHub PAT to commit fleet-repo'
    required: true
  git-username:
    description: 'Git username'
    required: true
  git-email:
    description: 'Git e-mail'
    required: true
  fleet-repo:
    description: 'Fleet repo'
    required: true
  fleet-values-path:
    description: 'Fleet values.yaml path'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Test repository access
      shell: bash
      env:
        GITHUB_USERNAME: ${{ inputs.git-username }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPO: ${{ inputs.fleet-repo }}
        GITHUB_BRANCH: ${{ inputs.branch }}
      run: curl -o- https://raw.githubusercontent.com/alvelive/deploy/02573b4d7f4d9d857c712743d17c3e37e9bd7e3b/test_connectivity.sh | bash

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Clone Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.fleet-repo }}
        ref: ${{ inputs.branch }}
        token: ${{ inputs.github-token }}

    - name: Configure Git
      shell: bash
      env:
        GITHUB_USERNAME: ${{ inputs.git-username }}
        GITHUB_EMAIL: ${{ inputs.git-email }}
      run: curl -o- https://raw.githubusercontent.com/alvelive/deploy/02573b4d7f4d9d857c712743d17c3e37e9bd7e3b/configure_git.sh | bash

    - name: Replace content
      shell: bash
      env:
        REPOSITORY_NAME: ${{ inputs.repo }}
        COMMIT_SHA: ${{ inputs.commit-hash }}
        FLEET_VALUES_PATH: ${{ inputs.fleet-values-path }}
      run: curl -o- https://raw.githubusercontent.com/alvelive/deploy/02573b4d7f4d9d857c712743d17c3e37e9bd7e3b/replace_content.ts | bun -

    - name: Update Fleet
      shell: bash
      env:
        GITHUB_REPO: ${{ inputs.fleet-repo }}
        GITHUB_BRANCH: ${{ inputs.branch }}
        GITHUB_SHA: ${{ inputs.commit-hash }}
      run: curl -o- https://raw.githubusercontent.com/alvelive/deploy/02573b4d7f4d9d857c712743d17c3e37e9bd7e3b/commit_changes.sh | bash
